# Base URI to API
target_uri: 'http://localhost:3001/api/v1/'

# Determines if the request should be asynchronous
async_requests: true

# Request list
requests_meta: [
  {
    source: 'MedicalCenter1',
    request_type: 'consult',
    endpoint: 'consults',
    request_number: 1
  },
  # {source: 'MedicalCenter2', request_type: 'consult', request_number: 100}
  # {source: 'ClinicaBicentenario', request_type: 'exam', request_number: 420}
]
